### ISSUE TITLE
Help the ValueError error!

### ISSUE THREAD

**Issue by getengqing** [HolmesShuan/DeepID-I-Reimplement#1]
When I used your WebFace.caffemodel running the face_recognition.py, I got the error:
(1, 3, 144, 144)
Traceback (most recent call last):
  File "face_recognition.py", line 77, in <module>
    feature_1 = get_feature(DATA_BASE + filepath_1, mean_npy);
  File "face_recognition.py", line 25, in get_feature
    X = read_image(path, mean_blob);
  File "face_recognition.py", line 42, in read_image
    X[0,0,:,:] = image[:,:] - mean;
ValueError: could not broadcast input array from shape (128,128,3) into shape (128,128)

**Comment by HolmesShuan** [comment]
**Aaron_Eckhart_0001.jpg** on the project website is the standard test image format. Gray image will be used.
